/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author g6
 */
public class AccueilUI extends javax.swing.JPanel {
    private JButton creerEntrepriseButton = new JButton("Creer une entreprise");
    private JButton saisirOffreButton = new JButton("Saisir une offre");
    private JButton consulterOffreButton = new JButton("Consulter les offres");
    private JButton cancelButton = new JButton("Annuler");
    /**
     * Creates new form AccueilUI
     */
    public AccueilUI() {
        setBorder(new TitledBorder(new EtchedBorder(),"Gestion des offres de stage"));
        setLayout(new BorderLayout(5, 5));
        add(initButtons(), BorderLayout.CENTER); 
    }
    
    private JPanel initButtons() {
      JPanel panel = new JPanel();
      panel.setLayout(new FlowLayout(FlowLayout.CENTER, 3, 3));
      panel.add(creerEntrepriseButton);
      panel.add(saisirOffreButton);
      panel.add(consulterOffreButton);
      panel.add(cancelButton);

      creerEntrepriseButton.addActionListener(new ButtonHandler());
      saisirOffreButton.addActionListener(new ButtonHandler());
      consulterOffreButton.addActionListener(new ButtonHandler());
      cancelButton.addActionListener(new ButtonHandler());
      //list.addListSelectionListener(new OffreSelectionListener());
      
      return panel;
   }
    
     private class ButtonHandler implements ActionListener {
      @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
         String command = ((JButton) e.getSource()).getActionCommand();
         switch (command) {
         case "Creer une entreprise":
            new EntrepriseUI().setVisible(true);
            break;
         case "Saisir une offre":
            //setFieldData(iterator.suivant()); 
            break;
         case "Consulter les offres":
            new OffreUI().setVisible(true);
            break;
         case "Annuler":
            System.exit(0);
         default:
            JOptionPane.showMessageDialog(null,
            "invalid command");
         }
        }
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
